authors:
  heurtematte:
    name: Sébastien Heurtematte
    description: Creator
    avatar: https://github.com/heurtematte.png
  fredg02:
    name: Frederic Gurr
    description: Creator
    avatar: https://github.com/fredg02.png
  pstankie:
    name: Pawel Stankiewicz
    description: Creator
    avatar: https://github.com/pstankie.png